### ISSUE TITLE
Remove sensu qualifier from hemocyte

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#12] opened 2015-06-04 18:51 UTC
```
GO uses "hemocyte differentiation" with this:

[Term]
id: CL:0000387
name: hemocyte (sensu Nematoda and Protostomia)
namespace: cell
xref: FBbt:00005063
is_a: CL:0000519 ! phagocyte (sensu Nematoda and Protostomia)
relationship: capable_of GO:0035010 {source="PMID:18025161"} ! encapsulation of 
foreign target
relationship: develops_from CL:0000385 ! prohemocyte (sensu Nematoda and 
Protostomia)

can we relabel this "hemocyte". We don't think it's ambiguous 
(go_obo2owl_mtg_2013)

Consider adding taxon constraint

Also add xref for:
http://en.wikipedia.org/wiki/Hemocyte

```

Original issue reported on code.google.com by `cmung...@gmail.com` on 29 Jan 2013 at 10:35

**Comment by paolaroncaglia** [comment] 2021-08-25 15:57
This request from @cmungall hasn't been addressed yet. I believe it may still be relevant for GO, so commenting here to prevent staleness.

**Comment by bvarner-ebi** [comment] 2022-07-25 10:22
Related ticket: https://github.com/obophenotype/cell-ontology/issues/1615

Should CL:0000387 'hemocyte (sensu Arthropoda)' be relabelled to 'hemocyte' or should a new term for 'hemocyte' be created (#1615)?

**Comment by gouttegd** [comment] 2022-07-25 18:42
> Current label for CL:0000387 is 'hemocyte (sensu Arthropoda)'. Is this the same as (sensu Nematoda and Protostomia)?

`sensu Arthropoda` is a little bit more precise.

I am not sure about removing `sensu Arthropoda` from CL:0000387’s label. The problem is that, as far as I know, “hemoctes” do not exist only in arthropods. The term is also used to refer to similar cells in other, non-insect invertebrates (e.g. mollusks, [González et al., 2019](https://doi.org/10.1016/B978-0-12-809633-8.20896-0)). But our CL:0000387 term is specifically about arthropod hemocytes (it has an explicit taxon restriction, `only_in_taxon some Arthropoda`). So maybe it’s a good idea to keep the label as it is to make it apparent that the term is arthropod-specific?

Alternatively, since the term “hemocyte” is used beyond arthropods, we could also update our CL:0000387 to broaden the taxon restriction and make it applicable to hemocytes of all invertebrates, not only arthropods. That would have my preference, I think. But a concern with that is that in GO `hemocyte differentiation` (which refers to CL:0000387) _also_ has a taxon restriction to arthropods, so if want to broaden our term we should probably coordinate that move with GO. I think it would be weird, and needlessly confusing, if “hemocyte” in CL meant hemocytes from all invertebrates but “hemocyte differentiation” in GO meant differentiation of arthropod hemocytes…

**Comment by bvarner-ebi** [comment] 2022-07-26 08:47
> Alternatively, since the term “hemocyte” is used beyond arthropods, we could also update our CL:0000387 to broaden the taxon restriction and make it applicable to hemocytes of all invertebrates, not only arthropods. 

Thank you for the feedback, @gouttegd. My concern with this is that someone may already be using CL:0000387 with the restriction in mind, so I wouldn't want to change the meaning of the term. So perhaps we leave the label as it is. Do the axioms referring to sensu Nematoda and Protostomia pose a problem if we leave the label as it is?

**Comment by gouttegd** [comment] 2022-07-26 10:02
> My concern with this is that someone may already be using CL:0000387 with the restriction in mind, so I wouldn't want to change the meaning of the term.

Agreed.

> Do the axioms referring to sensu Nematoda and Protostomia pose a problem if we leave the label as it is?

I don’t think so. `Arthropoda` is included in `Nematoda and Protostomia`, so those axioms are true even if we keep restricting `hemocyte` to arthropods.

For example, `'hemocyte (sensu Arthropoda)' develops_from some 'prohemocyte (sensu Nematoda and Protostoma)'`: it is true that an (insect) hemocyte develops from an (invertebrate) prohemocyte.

It _is_ somewhat confusing that `hemocyte` is restricted to arthropods while its direct progenitor has a broader scope, but it’s not wrong.

Since we don’t want to change the scope of `hemocyte`, maybe at some point we will need to introduce a new class `hemocyte (sensu Nematoda and Protostomia)` to encompass _all_ hemocytes. But I’d be reluctant to do so until the need for such a term arises.

**Comment by bvarner-ebi** [comment] 2022-07-26 10:22
Thank you for the insight, @gouttegd! I think it is appropriate to leave the term as it is right now and to close this ticket.

**Closed by bvarner-ebi** 2022-07-26 10:22 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
