### ISSUE TITLE
CL terms with missing definitions

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/cell-ontology#649] opened 2020-04-29 06:09 UTC
Here is a [spreadsheet](https://docs.google.com/spreadsheets/d/1Bcu6O5hgqAxTMcha_pDv4yZCQ8kTlMiLlb8o4b_2He0/edit#gid=1116044123) with terms that are missing definitions in CL.

(I don't know how to bring in the labels- can anyone do that?)

Hopefully we can all work through this list and add definitions.

**Comment by nicolevasilevsky** [comment] 2020-04-29 06:10
related to #632

**Comment by nicolevasilevsky** [comment] 2020-05-06 00:19
Kent added the labels [here](https://docs.google.com/spreadsheets/d/1Bcu6O5hgqAxTMcha_pDv4yZCQ8kTlMiLlb8o4b_2He0/edit#gid=308594775)

**Comment by paolaroncaglia** [comment] 2022-04-29 12:17
Closing as a duplicate of https://github.com/obophenotype/cell-ontology/issues/1262.

**Closed by paolaroncaglia** 2022-04-29 12:17 UTC
Labels: definition request
