### ISSUE TITLE
[Typo/Bug] role defintion "is creating a cyclic dependancy"

### ISSUE THREAD

**Issue by gabbysantos** [obophenotype/cell-ontology#2065] opened 2023-07-17 08:49 UTC
**CL term**
CHEBI_50906 mapped to BFO_0000023 

**Description of typo, bug or error**

This mapping is creating a cyclic dependancy between equivalence modelling and parent/child modelling

**Comment by bvarner-ebi** [comment] 2023-07-20 13:29
@gabbysantos, thank you for this issue.

After investigating with @anitacaron, it appears the logical definition of [role](http://purl.obolibrary.org/obo/BFO_0000023) comes from GO.

[I opened a ticket in GO for them to investigate](https://github.com/geneontology/go-ontology/issues/25821). They will need to fix the issue there -- if we only make the change in CL, it will reappear with every refreshed import.

I will update this ticket appropriately, but feel free to also track [the GO issue](https://github.com/geneontology/go-ontology/issues/25821).

**Comment by gabbysantos** [comment] 2023-07-20 15:17
thanks for looking into it

**Comment by bvarner-ebi** [comment] 2023-08-01 09:29
@gabbysantos, according to [this comment](https://github.com/geneontology/go-ontology/issues/25821#issuecomment-1658793378), this issue should be resolved in the August GO release. Depending on the actual release date, the changes will merge into CL in the August or September CL release.

Closing this issue. If the issue is not resolved by the September CL release, feel free to reopen or create a new issue.

**Closed by bvarner-ebi** 2023-08-01 09:29 UTC
Labels: bug, typo
