### ISSUE TITLE
Align thymocyte / DN T Cell with MP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/cell-ontology#31] opened 2015-06-04 18:51 UTC
```
See: 
https://sourceforge.net/tracker/?func=detail&atid=1109502&aid=3610968&group_id=7
6834


```

Original issue reported on code.google.com by `cmung...@gmail.com` on 20 Apr 2013 at 8:07

**Comment by addiehl** [comment] 2021-09-28 19:31
Closing.  Will reopen if a better description of the problem is provided.  I suspect MP is the problem, not CL in any case.

**Closed by addiehl** 2021-09-28 19:31 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
